### ISSUE TITLE
Cannot evaluate expression on value definition

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/scala-debug-adapter#103] opened 2021-09-23 20:19 UTC
I originally brought this up in https://github.com/scalameta/metals/pull/2959 while testing out the new code evaluation in Metals. I noticed that given a situation where you set a breakpoint before a variable is assigned, any evaluation is then blocked since it seems to not find that variable. A picture is worth a thousand words so you can see what I mean here:

<img width="1019" alt="Screenshot 2021-09-23 at 18 33 52" src="https://user-images.githubusercontent.com/13974112/134577427-4d09c74b-7560-406c-9772-8b773f4d8eca.png">

Notice that I'm stopped on the line containing `val y = x * 3`. I'm just trying to evaluate `3 * 6` here, and I'd expect that to work instead of getting the message about `not found: value y`.

The same thing happens if you try to access another variable that should already be assigned like `x` in this example:

<img width="1017" alt="Screenshot 2021-09-23 at 19 03 52" src="https://user-images.githubusercontent.com/13974112/134577616-ee5ae877-cecf-4331-a266-52872430e8bb.png">

Notice that it is there when looking at the variables, but when I try to access it via just `x` where the expressions are entered at the bottom, I again see the message.

I tested this with the pr in Metals here: https://github.com/scalameta/metals/pull/2959 while using [nvim-metals](https://github.com/scalameta/nvim-metals), which integrates with [nvim-dap](https://github.com/mfussenegger/nvim-dap).

As a total aside, great job on this so far. It's fantastic to see this working. In the above examples if I just step over once, then everything works.

![2021-09-23 18 27 03](https://user-images.githubusercontent.com/13974112/134577955-be68f4b8-6ab4-427d-888f-ec0159d37d34.gif)

**Comment by tgodzik** [comment] 2021-10-01 09:41
I can still reproduce the issue in Metals, can you take a second look @tdudzik ?

**Comment by ckipp01** [comment] 2021-10-01 09:54
> I can still reproduce the issue in Metals, can you take a second look @tdudzik ?

Just a sanity check, but make sure you have the new bloop that it brought in running and not the old one. I've made that mistake more than once when testing this out 😆

**Comment by tdudzik** [comment] 2021-10-01 10:17
Actually, it doesn't always work. It seems there were two issues with that case and I've fixed only one of them. The other one should be fixed soon.

**Comment by adpi2** [comment] 2021-10-01 11:26
@tdudzik Can you share the reproduction case?

**Comment by tdudzik** [comment] 2021-10-01 11:33
@adpi2 it seems that it works only when a value/variable is defined but it's not used, so e.g.:
it's going to work:

```scala
val a = 1 // breakpoint
println("Hello, World!")
```

it's not going to work:
```scala
val a = 1 // breakpoint
println(a)
```

The reason is that in `InsertExpression` compilation phase expression is wrapped in a block so the second example will be converted to something like this:
```scala
{
1 + 2 // expression
val a = 1 
}
println(a)
```
and then the value `a` is not accessible in the line `println(a)` and because of that error is returned.

**Comment by tgodzik** [comment] 2021-10-01 12:22
Do we need to have `val a = 1 ` in the block? Could we move it outside it?

**Closed** 2021-10-06 11:34 UTC
Labels: bug, expression evaluation
