### ISSUE TITLE
DebugSession creation fails

### ISSUE THREAD

**Issue by minedeljkovic** [scalacenter/scala-debug-adapter#158] opened 2021-11-17 16:30 UTC
I'm using latest (0.10.8+) version of metals in VSCode devcontainer, with sbt bsp integration, and debugger won't start (gets stuck in initialization).

After some investigation, I discovered that [this call](https://github.com/scalacenter/scala-debug-adapter/blob/c589b2f3eb2b277b6f6cd9d0ffebbb3ae89478d0/core/src/main/scala/ch/epfl/scala/debugadapter/internal/DebugSession.scala#L283) to create `DebugSession` fails with:
```
java.nio.file.FileSystemAlreadyExistsException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
        at ch.epfl.scala.debugadapter.internal.IO$.withinJarFile(IO.scala:13)
        at ch.epfl.scala.debugadapter.ClassJar.within(ClassSystem.scala:16)
        at ch.epfl.scala.debugadapter.internal.ClassEntryLookUp$.$anonfun$apply$2(ClassEntryLookUp.scala:141)
        at scala.collection.immutable.List.flatMap(List.scala:366)
        at ch.epfl.scala.debugadapter.internal.ClassEntryLookUp$.apply(ClassEntryLookUp.scala:140)
        at ch.epfl.scala.debugadapter.internal.SourceLookUpProvider$.$anonfun$apply$1(SourceLookUpProvider.scala:64)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:66)
        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

0.10.7 and earlier versions of metals work with no issues in the same environment. 

The issue was first discussed [here on gitter](https://gitter.im/scalameta/metals?at=6194c8e1a38ef653ee01946f)

**Comment by adpi2** [comment] 2021-11-18 08:52
Thanks for the bug report!

Copying here the part of discussion from gitter that could fix the problem.

> Tobias Roeser @lefou Nov 17 11:59
I've seed this error message in mill before. This is an issue with ZipFileSystemProvider, though I don't remember whether it was because of concurrent access or something else. We solved it be using the older ZipOutputStream I think

>Milos Nedeljkovic @minedeljkovic Nov 17 12:04
It seems it is concurrency related, because it behaves flaky on simple (HelloWorld like) applications, where sometime succeeds, but consistently fails on anything more involved.

>Tobias Roeser @lefou Nov 17 12:04
[com-lihaoyi/mill#1483](https://github.com/com-lihaoyi/mill/pull/1483)
I linked our PR. We refactored to use a ZipInputStream.

**Comment by adpi2** [comment] 2022-10-21 09:23
Should be fixed by https://github.com/scalacenter/scala-debug-adapter/pull/283 which is released in https://github.com/scalacenter/scala-debug-adapter/releases/tag/v3.0.1

If this error happens again, I would appreciate if someone could open an issue with a reproduction step.

**Closed by adpi2** 2022-10-21 09:23 UTC
